server:
    port: 8081

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
        username:
        password:
    jpa:
        hibernate:
            ddl-auto: validate
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                default_batch_fetch_size: 1000
    devtools:
        livereload:
            enabled: true

    servlet:
        multipart:
            # 파일 한 개당 최대 사이즈
            maxFileSize: 20MB
            # 요청당 최대 파일 크기
            maxRequestSize: 100MB

# 상품 이미지 업로드 경로
itemImgLocation: C:/shop/item

# 리소스 업로드 경로
uploadPath: file:///C:/shop/

logging:
    level:
        org:
            hibernate:
                type:
                    descripter:
                        sql: trace
